### ISSUE TITLE
Download/install size of Flatpak is *much* larger after MPV upgrade

### ISSUE THREAD

**Issue by dweymouth** [flathub/io.github.dweymouth.supersonic#42]
The download and install size of the Flatpak went *way* up since upgrading to the latest MPV and adding the new build dependencies. Is there maybe a way to trim this back down some again? Or is there any reason not to just stay on the old MPV version, at least for the time being? Unless it has a major security issue or is unsupported, it seemed to be still working fine?

<img width="982" alt="image" src="https://github.com/flathub/io.github.dweymouth.supersonic/assets/5303666/fd715660-bbe2-4b4a-a581-1d33d9807612">

**Comment by anarcat** [comment]
> Is there maybe a way to trim this back down some again?

Maybe! Honestly, it's been so much work just getting this to work that I've mostly rested on my laurels, as we say in french, and haven't looked any further.

But it should be possible to trim down the build, typically that involves removing superfluous libs, header files, or .a files and so on. Not sure, this is, after all, my first flatpak. :p

The screenshot you pasted shows an install size of 513MB and a download size of 222MB, do you remember what that was before? What's a "success" number here?

> Or is there any reason not to just stay on the old MPV version, at least for the time being? Unless it has a major security issue or is unsupported, it seemed to be still working fine?

My approach over this has been to hook up the normal flathub bots to check for dependency updates, and just update as soon as there's a new upstream version. Doing anything else would require me to do either of those:

 1. ignore pull requests from the bot repeatedly
 2. pick and choose which pull request to accept, and repeatedly blocking the others
 3. disabling automated pull requests

All those options seem pretty bad: ignoring the pull request will just lead to alert fatigue. Ignoring some and applying others is going to be a lot of work, I don't actually know if i can make the bot ignore some, and then what? When is it time to update?

And disabling updates altogether seem like a recipe for disaster, I wouldn't personally go there.

Interestingly, [mpv itself is less than 150MB in installed size](https://flathub.org/en-GB/apps/io.mpv.Mpv), so maybe there's an easy way to get there, probably by taking inspiration from [their yaml file](https://github.com/flathub/io.mpv.Mpv/blob/master/io.mpv.Mpv.yml).

**Comment by anarcat** [comment]
> Interestingly, [mpv itself is less than 150MB in installed size](https://flathub.org/en-GB/apps/io.mpv.Mpv), so maybe there's an easy way to get there, probably by taking inspiration from [their yaml file](https://github.com/flathub/io.mpv.Mpv/blob/master/io.mpv.Mpv.yml).

i just did that and it seems like mpv builds itself rather differently than what we do here.  Here I build the SPIRV, glslang under libplacebo, then that gets used by mpv, but in mpv libplacebo is built on its own, then spirv and glslang are built under shaderc, which is under libplacebo. I didn't do that precisely because I thought it would add another dependency (and more space!) but maybe that's the reason for the discrepancy.

**Comment by anarcat** [comment]
i tried to build libplacebo like mpv does it in #43.

**Comment by dweymouth** [comment]
> The screenshot you pasted shows an install size of 513MB and a download size of 222MB, do you remember what that was before? What's a "success" number here?


I'm pretty sure the download size was under 50 MB before and the install size maybe 80 or so? It's not a big deal, was just wondering if there might be an easy way to reclaim some of the size savings. I also guess Flatpak users are used to large install sizes because of each package bundling its own dependencies 🤷‍♂️

**Comment by anarcat** [comment]
thanks for the update, and nah, we should figure out a way to fix this, i don't care what people feel flatpak should be doing, but this is wrong.

**Comment by anarcat** [comment]
ah, found a promising lead in https://github.com/flathub/io.github.dweymouth.supersonic/pull/43/commits/3957f0e3e6cade185838c4aadfcde1f87d087ca3 but i need to step away, there should be a build ready to try in a few minutes in any case.

**Comment by anarcat** [comment]
ugh. that build is *bigger* than the original:

```
anarcat@angela:~$ flatpak list --columns=name,size,version,branch
Name                                            Installed size           Version                 Branch
Supersonic                                      538,4 MB       0.8.1                   stable
Supersonic                                      607,6 MB       0.8.1                   test
```

**Comment by anarcat** [comment]
figured it out, the SPIRV  `.a` files are 300+MB, #43 fixes this and will be merged as soon as the last build completes (i did a rebase to cleanup history a bit, but no change since last successful build in https://github.com/flathub/io.github.dweymouth.supersonic/pull/43#issuecomment-1848965604:

```
anarcat@angela:~$ flatpak install --user https://dl.flathub.org/build-repo/69631/io.github.dweymouth.supersonic.flatpakref

io.github.dweymouth.supersonic permissions:
    ipc                     network       pulseaudio       x11       dri       file access [1]      dbus access [2]
    bus ownership [3]

    [1] xdg-run/keyring
    [2] org.freedesktop.Notifications, org.freedesktop.secrets, org.gnome.keyring.SystemPrompter, org.kde.StatusNotifierWatcher,
        org.mpris.MediaPlayer2.Player
    [3] org.mpris.MediaPlayer2.Supersonic


        ID                                        Branch            Op            Remote                       Download
 1. [✓] io.github.dweymouth.supersonic            test              i             supersonic-origin            24,2 MB / 24,3 MB

Installation complete.
```
