### ISSUE TITLE
Please add permissions for pipewire

### ISSUE THREAD

**Issue by whorfin** [flathub/io.github.dweymouth.supersonic#44]
In order to access pipewire devices without going through Pulse, we need to add
```
filesystems=xdg-run/pipewire-0:ro
```

For now adding this with `flatpak override` allows me access but it would be very nice to have this available by default
Note - if one is in a configuration where you see  double-device listings (once under pipewire, once for pulse-wrapped), one can disable pulseaudio socket permissions in eg Flatseal to just see pipewire.
Probably don't want to do that by default

**Comment by anarcat** [comment]
that sounds like a great idea, can you provide a PR? following this link should get you started:

https://github.com/flathub/io.github.dweymouth.supersonic/edit/master/io.github.dweymouth.supersonic.yml
